# -*- coding: utf-8 -*-
"""WebsiteTestCode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_-6PZS1c7P-A9Cl5CsdiXNKhROiOlIIo
"""

import streamlit as st

st.title('Welcome App')

name = st.text_input("Hello, what is your name?")

if st.button('Submit'):
    st.write(f"Hello {name}, Welcome!")